### ISSUE TITLE
Complete CandidateListTile design mock

### ISSUE THREAD

**Issue by otech47** [setzeus/setgov#12]
- [ ] Candidate Name
- [ ] Candidate picture
- [ ] Democrat or republican

**Comment by brgarciarivas** [comment]
![screen shot 2016-10-18 at 1 32 00 am](https://cloud.githubusercontent.com/assets/6628741/19482020/d221c24a-951d-11e6-88a2-592315af514b.png)

**Comment by sinnott-balin** [comment]
Post designs here when they are finalized.

**Comment by brgarciarivas** [comment]
![screen shot 2016-10-19 at 9 37 06 am](https://cloud.githubusercontent.com/assets/6628741/19520867/a9093c0e-95df-11e6-94c3-6c6b33c5d7c4.png)
